# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'merge_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_merge(object):
    def setupUi(self, merge):
        merge.setObjectName("merge")
        merge.resize(1375, 902)
        self.centralwidget = QtWidgets.QWidget(merge)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_open_image = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_open_image.sizePolicy().hasHeightForWidth())
        self.pushButton_open_image.setSizePolicy(sizePolicy)
        self.pushButton_open_image.setStyleSheet("background-color: rgb(255, 189, 176);")
        self.pushButton_open_image.setObjectName("pushButton_open_image")
        self.horizontalLayout_7.addWidget(self.pushButton_open_image)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.lineEdit_img_w = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_img_w.setObjectName("lineEdit_img_w")
        self.horizontalLayout_7.addWidget(self.lineEdit_img_w)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.pushButton_more_info = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_more_info.setStyleSheet("background-color: rgb(255, 235, 201);")
        self.pushButton_more_info.setObjectName("pushButton_more_info")
        self.horizontalLayout_7.addWidget(self.pushButton_more_info)
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setStyleSheet("background-color: rgb(255, 104, 93);")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.horizontalLayout_7.addWidget(self.pushButton_exit)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_8.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7.setStretch(3, 1)
        self.horizontalLayout_7.setStretch(6, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_hsv_src_image = QtWidgets.QLabel(self.tab)
        self.label_hsv_src_image.setStyleSheet("background-color: rgb(249, 252, 255);")
        self.label_hsv_src_image.setScaledContents(True)
        self.label_hsv_src_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hsv_src_image.setObjectName("label_hsv_src_image")
        self.gridLayout_3.addWidget(self.label_hsv_src_image, 0, 0, 1, 1)
        self.image_hsv_draw = QtWidgets.QLabel(self.tab)
        self.image_hsv_draw.setStyleSheet("background-color: rgb(249, 252, 255);")
        self.image_hsv_draw.setScaledContents(True)
        self.image_hsv_draw.setAlignment(QtCore.Qt.AlignCenter)
        self.image_hsv_draw.setObjectName("image_hsv_draw")
        self.gridLayout_3.addWidget(self.image_hsv_draw, 1, 0, 1, 1)
        self.image_hsv_mask = QtWidgets.QLabel(self.tab)
        self.image_hsv_mask.setStyleSheet("background-color: rgb(249, 252, 255);")
        self.image_hsv_mask.setScaledContents(True)
        self.image_hsv_mask.setAlignment(QtCore.Qt.AlignCenter)
        self.image_hsv_mask.setObjectName("image_hsv_mask")
        self.gridLayout_3.addWidget(self.image_hsv_mask, 0, 1, 1, 1)
        self.textEdit_hsv_info = QtWidgets.QTextEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_hsv_info.sizePolicy().hasHeightForWidth())
        self.textEdit_hsv_info.setSizePolicy(sizePolicy)
        self.textEdit_hsv_info.setObjectName("textEdit_hsv_info")
        self.gridLayout_3.addWidget(self.textEdit_hsv_info, 1, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_3)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_hs = QtWidgets.QLabel(self.tab)
        self.label_hs.setStyleSheet("background-color: rgb(105, 153, 255);")
        self.label_hs.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hs.setObjectName("label_hs")
        self.gridLayout_5.addWidget(self.label_hs, 10, 0, 1, 1)
        self.label_lh = QtWidgets.QLabel(self.tab)
        self.label_lh.setStyleSheet("background-color: rgb(176, 211, 255);")
        self.label_lh.setAlignment(QtCore.Qt.AlignCenter)
        self.label_lh.setObjectName("label_lh")
        self.gridLayout_5.addWidget(self.label_lh, 6, 0, 1, 1)
        self.checkBox_hsv_inv = QtWidgets.QCheckBox(self.tab)
        self.checkBox_hsv_inv.setObjectName("checkBox_hsv_inv")
        self.gridLayout_5.addWidget(self.checkBox_hsv_inv, 12, 1, 1, 1)
        self.label_hv = QtWidgets.QLabel(self.tab)
        self.label_hv.setStyleSheet("background-color: rgb(105, 153, 255);")
        self.label_hv.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hv.setObjectName("label_hv")
        self.gridLayout_5.addWidget(self.label_hv, 11, 0, 1, 1)
        self.horizontalSlider_hh = QtWidgets.QSlider(self.tab)
        self.horizontalSlider_hh.setMaximum(180)
        self.horizontalSlider_hh.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_hh.setObjectName("horizontalSlider_hh")
        self.gridLayout_5.addWidget(self.horizontalSlider_hh, 9, 1, 1, 1)
        self.horizontalSlider_ls = QtWidgets.QSlider(self.tab)
        self.horizontalSlider_ls.setMaximum(255)
        self.horizontalSlider_ls.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_ls.setObjectName("horizontalSlider_ls")
        self.gridLayout_5.addWidget(self.horizontalSlider_ls, 7, 1, 1, 1)
        self.checkBox_hsv_smooth = QtWidgets.QCheckBox(self.tab)
        self.checkBox_hsv_smooth.setObjectName("checkBox_hsv_smooth")
        self.gridLayout_5.addWidget(self.checkBox_hsv_smooth, 12, 0, 1, 1)
        self.horizontalSlider_lv = QtWidgets.QSlider(self.tab)
        self.horizontalSlider_lv.setMaximum(255)
        self.horizontalSlider_lv.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_lv.setObjectName("horizontalSlider_lv")
        self.gridLayout_5.addWidget(self.horizontalSlider_lv, 8, 1, 1, 1)
        self.label_hsv_la = QtWidgets.QLabel(self.tab)
        self.label_hsv_la.setStyleSheet("background-color: rgb(255, 212, 199);")
        self.label_hsv_la.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hsv_la.setObjectName("label_hsv_la")
        self.gridLayout_5.addWidget(self.label_hsv_la, 13, 0, 1, 1)
        self.lineEdit_hsv_la = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_hsv_la.setObjectName("lineEdit_hsv_la")
        self.gridLayout_5.addWidget(self.lineEdit_hsv_la, 13, 1, 1, 1)
        self.label_hh = QtWidgets.QLabel(self.tab)
        self.label_hh.setStyleSheet("background-color: rgb(105, 153, 255);")
        self.label_hh.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hh.setObjectName("label_hh")
        self.gridLayout_5.addWidget(self.label_hh, 9, 0, 1, 1)
        self.label_lv = QtWidgets.QLabel(self.tab)
        self.label_lv.setStyleSheet("background-color: rgb(176, 211, 255);")
        self.label_lv.setAlignment(QtCore.Qt.AlignCenter)
        self.label_lv.setObjectName("label_lv")
        self.gridLayout_5.addWidget(self.label_lv, 8, 0, 1, 1)
        self.label_hsv_ha = QtWidgets.QLabel(self.tab)
        self.label_hsv_ha.setStyleSheet("background-color: rgb(255, 158, 120);")
        self.label_hsv_ha.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hsv_ha.setObjectName("label_hsv_ha")
        self.gridLayout_5.addWidget(self.label_hsv_ha, 14, 0, 1, 1)
        self.horizontalSlider_hv = QtWidgets.QSlider(self.tab)
        self.horizontalSlider_hv.setMaximum(255)
        self.horizontalSlider_hv.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_hv.setObjectName("horizontalSlider_hv")
        self.gridLayout_5.addWidget(self.horizontalSlider_hv, 11, 1, 1, 1)
        self.horizontalSlider_lh = QtWidgets.QSlider(self.tab)
        self.horizontalSlider_lh.setMaximum(180)
        self.horizontalSlider_lh.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_lh.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_lh.setObjectName("horizontalSlider_lh")
        self.gridLayout_5.addWidget(self.horizontalSlider_lh, 6, 1, 1, 1)
        self.horizontalSlider_hs = QtWidgets.QSlider(self.tab)
        self.horizontalSlider_hs.setMaximum(255)
        self.horizontalSlider_hs.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_hs.setObjectName("horizontalSlider_hs")
        self.gridLayout_5.addWidget(self.horizontalSlider_hs, 10, 1, 1, 1)
        self.pushButton_hsv_export = QtWidgets.QPushButton(self.tab)
        self.pushButton_hsv_export.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_hsv_export.setObjectName("pushButton_hsv_export")
        self.gridLayout_5.addWidget(self.pushButton_hsv_export, 15, 0, 1, 2)
        self.label_ls = QtWidgets.QLabel(self.tab)
        self.label_ls.setStyleSheet("background-color: rgb(176, 211, 255);")
        self.label_ls.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ls.setObjectName("label_ls")
        self.gridLayout_5.addWidget(self.label_ls, 7, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_lv_value = QtWidgets.QLabel(self.tab)
        self.label_lv_value.setObjectName("label_lv_value")
        self.gridLayout_2.addWidget(self.label_lv_value, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setStyleSheet("")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 2, 1, 1)
        self.label_ls_value = QtWidgets.QLabel(self.tab)
        self.label_ls_value.setObjectName("label_ls_value")
        self.gridLayout_2.addWidget(self.label_ls_value, 2, 1, 1, 1)
        self.label_lh_value = QtWidgets.QLabel(self.tab)
        self.label_lh_value.setObjectName("label_lh_value")
        self.gridLayout_2.addWidget(self.label_lh_value, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setStyleSheet("")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setStyleSheet("")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_hh_value = QtWidgets.QLabel(self.tab)
        self.label_hh_value.setObjectName("label_hh_value")
        self.gridLayout_2.addWidget(self.label_hh_value, 1, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setStyleSheet("")
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 2, 1, 1)
        self.label_hs_value = QtWidgets.QLabel(self.tab)
        self.label_hs_value.setObjectName("label_hs_value")
        self.gridLayout_2.addWidget(self.label_hs_value, 2, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setStyleSheet("")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 2, 1, 1)
        self.label_hv_value = QtWidgets.QLabel(self.tab)
        self.label_hv_value.setObjectName("label_hv_value")
        self.gridLayout_2.addWidget(self.label_hv_value, 3, 3, 1, 1)
        self.label_hsv_value = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_hsv_value.sizePolicy().hasHeightForWidth())
        self.label_hsv_value.setSizePolicy(sizePolicy)
        self.label_hsv_value.setObjectName("label_hsv_value")
        self.gridLayout_2.addWidget(self.label_hsv_value, 0, 0, 1, 2)
        self.gridLayout_5.addLayout(self.gridLayout_2, 0, 0, 1, 2)
        self.lineEdit_hsv_ha = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_hsv_ha.setObjectName("lineEdit_hsv_ha")
        self.gridLayout_5.addWidget(self.lineEdit_hsv_ha, 14, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_5.addLayout(self.verticalLayout_3, 2, 0, 1, 1)
        self.pushButton_hsv_cancle = QtWidgets.QPushButton(self.tab)
        self.pushButton_hsv_cancle.setObjectName("pushButton_hsv_cancle")
        self.gridLayout_5.addWidget(self.pushButton_hsv_cancle, 1, 0, 1, 1)
        self.pushButton_hsv_set_value = QtWidgets.QPushButton(self.tab)
        self.pushButton_hsv_set_value.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.pushButton_hsv_set_value.setObjectName("pushButton_hsv_set_value")
        self.gridLayout_5.addWidget(self.pushButton_hsv_set_value, 1, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_5)
        self.horizontalLayout_3.setStretch(0, 4)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_bi_src_image = QtWidgets.QLabel(self.tab_2)
        self.label_bi_src_image.setStyleSheet("background-color: rgb(249, 252, 255);")
        self.label_bi_src_image.setScaledContents(True)
        self.label_bi_src_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_bi_src_image.setObjectName("label_bi_src_image")
        self.gridLayout_6.addWidget(self.label_bi_src_image, 0, 0, 1, 1)
        self.textEdit_bi_info = QtWidgets.QTextEdit(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_bi_info.sizePolicy().hasHeightForWidth())
        self.textEdit_bi_info.setSizePolicy(sizePolicy)
        self.textEdit_bi_info.setObjectName("textEdit_bi_info")
        self.gridLayout_6.addWidget(self.textEdit_bi_info, 1, 1, 1, 1)
        self.image_bi_mask = QtWidgets.QLabel(self.tab_2)
        self.image_bi_mask.setStyleSheet("background-color: rgb(249, 252, 255);")
        self.image_bi_mask.setScaledContents(True)
        self.image_bi_mask.setAlignment(QtCore.Qt.AlignCenter)
        self.image_bi_mask.setObjectName("image_bi_mask")
        self.gridLayout_6.addWidget(self.image_bi_mask, 0, 1, 1, 1)
        self.image_bi_draw = QtWidgets.QLabel(self.tab_2)
        self.image_bi_draw.setStyleSheet("background-color: rgb(249, 252, 255);")
        self.image_bi_draw.setScaledContents(True)
        self.image_bi_draw.setAlignment(QtCore.Qt.AlignCenter)
        self.image_bi_draw.setObjectName("image_bi_draw")
        self.gridLayout_6.addWidget(self.image_bi_draw, 1, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_6)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lineEdit_bi_la = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_bi_la.setObjectName("lineEdit_bi_la")
        self.gridLayout_7.addWidget(self.lineEdit_bi_la, 3, 1, 1, 1)
        self.pushButton_bi_export = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_bi_export.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_bi_export.setObjectName("pushButton_bi_export")
        self.gridLayout_7.addWidget(self.pushButton_bi_export, 5, 0, 1, 2)
        self.checkBox_bi_inv = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_bi_inv.setObjectName("checkBox_bi_inv")
        self.gridLayout_7.addWidget(self.checkBox_bi_inv, 2, 1, 1, 1)
        self.lineEdit_bi_ha = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_bi_ha.setObjectName("lineEdit_bi_ha")
        self.gridLayout_7.addWidget(self.lineEdit_bi_ha, 4, 1, 1, 1)
        self.label_bi_ha = QtWidgets.QLabel(self.tab_2)
        self.label_bi_ha.setStyleSheet("background-color: rgb(255, 158, 120);")
        self.label_bi_ha.setAlignment(QtCore.Qt.AlignCenter)
        self.label_bi_ha.setObjectName("label_bi_ha")
        self.gridLayout_7.addWidget(self.label_bi_ha, 4, 0, 1, 1)
        self.checkBox_bi_smooth = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_bi_smooth.setObjectName("checkBox_bi_smooth")
        self.gridLayout_7.addWidget(self.checkBox_bi_smooth, 2, 0, 1, 1)
        self.label_bi_la = QtWidgets.QLabel(self.tab_2)
        self.label_bi_la.setStyleSheet("background-color: rgb(255, 212, 199);")
        self.label_bi_la.setAlignment(QtCore.Qt.AlignCenter)
        self.label_bi_la.setObjectName("label_bi_la")
        self.gridLayout_7.addWidget(self.label_bi_la, 3, 0, 1, 1)
        self.horizontalSlider_bi = QtWidgets.QSlider(self.tab_2)
        self.horizontalSlider_bi.setMinimum(1)
        self.horizontalSlider_bi.setMaximum(255)
        self.horizontalSlider_bi.setProperty("value", 15)
        self.horizontalSlider_bi.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_bi.setObjectName("horizontalSlider_bi")
        self.gridLayout_7.addWidget(self.horizontalSlider_bi, 1, 1, 1, 1)
        self.label_bi = QtWidgets.QLabel(self.tab_2)
        self.label_bi.setStyleSheet("background-color: rgb(255, 225, 248);")
        self.label_bi.setAlignment(QtCore.Qt.AlignCenter)
        self.label_bi.setObjectName("label_bi")
        self.gridLayout_7.addWidget(self.label_bi, 1, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_7)
        self.horizontalLayout_4.setStretch(0, 4)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.image_edge_draw = QtWidgets.QLabel(self.tab_3)
        self.image_edge_draw.setStyleSheet("background-color: rgb(249, 252, 255);")
        self.image_edge_draw.setScaledContents(True)
        self.image_edge_draw.setAlignment(QtCore.Qt.AlignCenter)
        self.image_edge_draw.setObjectName("image_edge_draw")
        self.gridLayout_8.addWidget(self.image_edge_draw, 1, 0, 1, 1)
        self.image_edge_mask = QtWidgets.QLabel(self.tab_3)
        self.image_edge_mask.setStyleSheet("background-color: rgb(249, 252, 255);")
        self.image_edge_mask.setScaledContents(True)
        self.image_edge_mask.setAlignment(QtCore.Qt.AlignCenter)
        self.image_edge_mask.setObjectName("image_edge_mask")
        self.gridLayout_8.addWidget(self.image_edge_mask, 0, 1, 1, 1)
        self.label_edge_src_image = QtWidgets.QLabel(self.tab_3)
        self.label_edge_src_image.setStyleSheet("background-color: rgb(249, 252, 255);")
        self.label_edge_src_image.setScaledContents(True)
        self.label_edge_src_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_edge_src_image.setObjectName("label_edge_src_image")
        self.gridLayout_8.addWidget(self.label_edge_src_image, 0, 0, 1, 1)
        self.textEdit_edge_info = QtWidgets.QTextEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_edge_info.sizePolicy().hasHeightForWidth())
        self.textEdit_edge_info.setSizePolicy(sizePolicy)
        self.textEdit_edge_info.setObjectName("textEdit_edge_info")
        self.gridLayout_8.addWidget(self.textEdit_edge_info, 1, 1, 1, 1)
        self.horizontalLayout_11.addLayout(self.gridLayout_8)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.lineEdit_edge_ha = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_edge_ha.setObjectName("lineEdit_edge_ha")
        self.gridLayout_9.addWidget(self.lineEdit_edge_ha, 4, 1, 1, 1)
        self.label_ha = QtWidgets.QLabel(self.tab_3)
        self.label_ha.setStyleSheet("background-color: rgb(255, 158, 120);")
        self.label_ha.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ha.setObjectName("label_ha")
        self.gridLayout_9.addWidget(self.label_ha, 4, 0, 1, 1)
        self.label_t2 = QtWidgets.QLabel(self.tab_3)
        self.label_t2.setStyleSheet("background-color: rgb(176, 211, 255);")
        self.label_t2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_t2.setObjectName("label_t2")
        self.gridLayout_9.addWidget(self.label_t2, 2, 0, 1, 1)
        self.pushButton_edge_export = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_edge_export.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_edge_export.setObjectName("pushButton_edge_export")
        self.gridLayout_9.addWidget(self.pushButton_edge_export, 5, 0, 1, 2)
        self.label_la_3 = QtWidgets.QLabel(self.tab_3)
        self.label_la_3.setStyleSheet("background-color: rgb(255, 212, 199);")
        self.label_la_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_la_3.setObjectName("label_la_3")
        self.gridLayout_9.addWidget(self.label_la_3, 3, 0, 1, 1)
        self.label_t1 = QtWidgets.QLabel(self.tab_3)
        self.label_t1.setStyleSheet("background-color: rgb(176, 211, 255);")
        self.label_t1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_t1.setObjectName("label_t1")
        self.gridLayout_9.addWidget(self.label_t1, 1, 0, 1, 1)
        self.horizontalSlider_t1 = QtWidgets.QSlider(self.tab_3)
        self.horizontalSlider_t1.setMaximum(255)
        self.horizontalSlider_t1.setProperty("value", 1)
        self.horizontalSlider_t1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_t1.setObjectName("horizontalSlider_t1")
        self.gridLayout_9.addWidget(self.horizontalSlider_t1, 1, 1, 1, 1)
        self.horizontalSlider_t2 = QtWidgets.QSlider(self.tab_3)
        self.horizontalSlider_t2.setMaximum(255)
        self.horizontalSlider_t2.setProperty("value", 40)
        self.horizontalSlider_t2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_t2.setObjectName("horizontalSlider_t2")
        self.gridLayout_9.addWidget(self.horizontalSlider_t2, 2, 1, 1, 1)
        self.lineEdit_edge_la = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_edge_la.setObjectName("lineEdit_edge_la")
        self.gridLayout_9.addWidget(self.lineEdit_edge_la, 3, 1, 1, 1)
        self.horizontalLayout_11.addLayout(self.gridLayout_9)
        self.horizontalLayout_11.setStretch(0, 4)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_11)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_flood_src_image = QtWidgets.QLabel(self.tab_4)
        self.label_flood_src_image.setStyleSheet("background-color: rgb(249, 252, 255);")
        self.label_flood_src_image.setScaledContents(True)
        self.label_flood_src_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_flood_src_image.setObjectName("label_flood_src_image")
        self.gridLayout_17.addWidget(self.label_flood_src_image, 0, 0, 1, 1)
        self.image_flood_mask = QtWidgets.QLabel(self.tab_4)
        self.image_flood_mask.setStyleSheet("background-color: rgb(249, 252, 255);")
        self.image_flood_mask.setScaledContents(True)
        self.image_flood_mask.setAlignment(QtCore.Qt.AlignCenter)
        self.image_flood_mask.setObjectName("image_flood_mask")
        self.gridLayout_17.addWidget(self.image_flood_mask, 0, 1, 1, 1)
        self.image_flood_draw = QtWidgets.QLabel(self.tab_4)
        self.image_flood_draw.setStyleSheet("background-color: rgb(249, 252, 255);")
        self.image_flood_draw.setScaledContents(True)
        self.image_flood_draw.setAlignment(QtCore.Qt.AlignCenter)
        self.image_flood_draw.setObjectName("image_flood_draw")
        self.gridLayout_17.addWidget(self.image_flood_draw, 1, 0, 1, 1)
        self.textEdit_flood_info = QtWidgets.QTextEdit(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_flood_info.sizePolicy().hasHeightForWidth())
        self.textEdit_flood_info.setSizePolicy(sizePolicy)
        self.textEdit_flood_info.setObjectName("textEdit_flood_info")
        self.gridLayout_17.addWidget(self.textEdit_flood_info, 1, 1, 1, 1)
        self.horizontalLayout_19.addLayout(self.gridLayout_17)
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.horizontalSlider_diff = QtWidgets.QSlider(self.tab_4)
        self.horizontalSlider_diff.setMinimum(1)
        self.horizontalSlider_diff.setMaximum(255)
        self.horizontalSlider_diff.setProperty("value", 30)
        self.horizontalSlider_diff.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_diff.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_diff.setObjectName("horizontalSlider_diff")
        self.gridLayout_18.addWidget(self.horizontalSlider_diff, 3, 1, 1, 1)
        self.pushButton_flood_export = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_flood_export.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_flood_export.setObjectName("pushButton_flood_export")
        self.gridLayout_18.addWidget(self.pushButton_flood_export, 4, 0, 1, 2)
        self.label_diff = QtWidgets.QLabel(self.tab_4)
        self.label_diff.setStyleSheet("background-color: rgb(176, 211, 255);")
        self.label_diff.setAlignment(QtCore.Qt.AlignCenter)
        self.label_diff.setObjectName("label_diff")
        self.gridLayout_18.addWidget(self.label_diff, 3, 0, 1, 1)
        self.pushButton_flood_cancle = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_flood_cancle.setObjectName("pushButton_flood_cancle")
        self.gridLayout_18.addWidget(self.pushButton_flood_cancle, 0, 0, 1, 2)
        self.horizontalLayout_19.addLayout(self.gridLayout_18)
        self.horizontalLayout_19.setStretch(0, 4)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_19)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_fig_area = QtWidgets.QLabel(self.tab_5)
        self.label_fig_area.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_fig_area.setScaledContents(True)
        self.label_fig_area.setAlignment(QtCore.Qt.AlignCenter)
        self.label_fig_area.setObjectName("label_fig_area")
        self.gridLayout.addWidget(self.label_fig_area, 1, 0, 1, 2)
        self.label_fig_line = QtWidgets.QLabel(self.tab_5)
        self.label_fig_line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_fig_line.setScaledContents(True)
        self.label_fig_line.setAlignment(QtCore.Qt.AlignCenter)
        self.label_fig_line.setObjectName("label_fig_line")
        self.gridLayout.addWidget(self.label_fig_line, 1, 2, 1, 2)
        self.label_fig_area_max_value = QtWidgets.QLabel(self.tab_5)
        self.label_fig_area_max_value.setObjectName("label_fig_area_max_value")
        self.gridLayout.addWidget(self.label_fig_area_max_value, 2, 0, 1, 1)
        self.lineEdit_fig_area_min_value = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_fig_area_min_value.setObjectName("lineEdit_fig_area_min_value")
        self.gridLayout.addWidget(self.lineEdit_fig_area_min_value, 2, 1, 1, 1)
        self.pushButton_open_data_file = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_open_data_file.setStyleSheet("background-color: rgb(85, 170, 127);")
        self.pushButton_open_data_file.setObjectName("pushButton_open_data_file")
        self.gridLayout.addWidget(self.pushButton_open_data_file, 0, 0, 1, 1)
        self.pushButton_fig_draw = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_fig_draw.setStyleSheet("color: rgb(255, 0, 255);")
        self.pushButton_fig_draw.setObjectName("pushButton_fig_draw")
        self.gridLayout.addWidget(self.pushButton_fig_draw, 0, 2, 1, 1)
        self.label_fig_line_max_value = QtWidgets.QLabel(self.tab_5)
        self.label_fig_line_max_value.setObjectName("label_fig_line_max_value")
        self.gridLayout.addWidget(self.label_fig_line_max_value, 2, 2, 1, 1)
        self.label_fig_line_min_value = QtWidgets.QLabel(self.tab_5)
        self.label_fig_line_min_value.setObjectName("label_fig_line_min_value")
        self.gridLayout.addWidget(self.label_fig_line_min_value, 3, 2, 1, 1)
        self.lineEdit_fig_line_min_value = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_fig_line_min_value.setObjectName("lineEdit_fig_line_min_value")
        self.gridLayout.addWidget(self.lineEdit_fig_line_min_value, 2, 3, 1, 1)
        self.label_fig_area_min_value = QtWidgets.QLabel(self.tab_5)
        self.label_fig_area_min_value.setObjectName("label_fig_area_min_value")
        self.gridLayout.addWidget(self.label_fig_area_min_value, 3, 0, 1, 1)
        self.lineEdit_fig_area_max_value = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_fig_area_max_value.setObjectName("lineEdit_fig_area_max_value")
        self.gridLayout.addWidget(self.lineEdit_fig_area_max_value, 3, 1, 1, 1)
        self.lineEdit_fig_line_max_value = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_fig_line_max_value.setObjectName("lineEdit_fig_line_max_value")
        self.gridLayout.addWidget(self.lineEdit_fig_line_max_value, 3, 3, 1, 1)
        self.label_fig_line_increment = QtWidgets.QLabel(self.tab_5)
        self.label_fig_line_increment.setObjectName("label_fig_line_increment")
        self.gridLayout.addWidget(self.label_fig_line_increment, 4, 2, 1, 1)
        self.lineEdit_fig_area_increment = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_fig_area_increment.setObjectName("lineEdit_fig_area_increment")
        self.gridLayout.addWidget(self.lineEdit_fig_area_increment, 4, 1, 1, 1)
        self.label_fig_area_increment = QtWidgets.QLabel(self.tab_5)
        self.label_fig_area_increment.setObjectName("label_fig_area_increment")
        self.gridLayout.addWidget(self.label_fig_area_increment, 4, 0, 1, 1)
        self.lineEdit_fig_line_increment = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_fig_line_increment.setObjectName("lineEdit_fig_line_increment")
        self.gridLayout.addWidget(self.lineEdit_fig_line_increment, 4, 3, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.tab_5, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout.addLayout(self.verticalLayout)
        merge.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(merge)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1375, 26))
        self.menubar.setObjectName("menubar")
        merge.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(merge)
        self.statusbar.setObjectName("statusbar")
        merge.setStatusBar(self.statusbar)

        self.retranslateUi(merge)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(merge)

    def retranslateUi(self, merge):
        _translate = QtCore.QCoreApplication.translate
        merge.setWindowTitle(_translate("merge", "merge"))
        self.pushButton_open_image.setText(_translate("merge", "open image"))
        self.label.setText(_translate("merge", "real width:"))
        self.pushButton_more_info.setText(_translate("merge", "MoreInfo"))
        self.pushButton_exit.setText(_translate("merge", "exit"))
        self.label_hsv_src_image.setText(_translate("merge", "imgae"))
        self.image_hsv_draw.setText(_translate("merge", "draw"))
        self.image_hsv_mask.setText(_translate("merge", "mask"))
        self.label_hs.setText(_translate("merge", "H_S:0"))
        self.label_lh.setText(_translate("merge", "L_H:0"))
        self.checkBox_hsv_inv.setText(_translate("merge", "inv"))
        self.label_hv.setText(_translate("merge", "H_V:0"))
        self.checkBox_hsv_smooth.setText(_translate("merge", " smooth"))
        self.label_hsv_la.setText(_translate("merge", "L_area:"))
        self.lineEdit_hsv_la.setText(_translate("merge", "2"))
        self.label_hh.setText(_translate("merge", "H_H:0"))
        self.label_lv.setText(_translate("merge", "L_V:0"))
        self.label_hsv_ha.setText(_translate("merge", "H_area:"))
        self.pushButton_hsv_export.setText(_translate("merge", "export"))
        self.label_ls.setText(_translate("merge", "L_S:0"))
        self.label_lv_value.setText(_translate("merge", "0"))
        self.label_6.setText(_translate("merge", "h_h:"))
        self.label_ls_value.setText(_translate("merge", "0"))
        self.label_lh_value.setText(_translate("merge", "0"))
        self.label_5.setText(_translate("merge", "l_v:"))
        self.label_4.setText(_translate("merge", "l_s:"))
        self.label_2.setText(_translate("merge", "l_h:"))
        self.label_hh_value.setText(_translate("merge", "0"))
        self.label_7.setText(_translate("merge", "h_s:"))
        self.label_hs_value.setText(_translate("merge", "0"))
        self.label_3.setText(_translate("merge", "h_v:"))
        self.label_hv_value.setText(_translate("merge", "0"))
        self.label_hsv_value.setText(_translate("merge", "hsv:"))
        self.lineEdit_hsv_ha.setText(_translate("merge", "100000000000"))
        self.pushButton_hsv_cancle.setText(_translate("merge", "cancle"))
        self.pushButton_hsv_set_value.setText(_translate("merge", "set value"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("merge", "HSV"))
        self.label_bi_src_image.setText(_translate("merge", "imgae"))
        self.image_bi_mask.setText(_translate("merge", "mask"))
        self.image_bi_draw.setText(_translate("merge", "draw"))
        self.lineEdit_bi_la.setText(_translate("merge", "2"))
        self.pushButton_bi_export.setText(_translate("merge", "export"))
        self.checkBox_bi_inv.setText(_translate("merge", "inv"))
        self.lineEdit_bi_ha.setText(_translate("merge", "100000000000"))
        self.label_bi_ha.setText(_translate("merge", "H_area:"))
        self.checkBox_bi_smooth.setText(_translate("merge", " smooth"))
        self.label_bi_la.setText(_translate("merge", "L_area:"))
        self.label_bi.setText(_translate("merge", "B:15"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("merge", "Binary"))
        self.image_edge_draw.setText(_translate("merge", "draw"))
        self.image_edge_mask.setText(_translate("merge", "mask"))
        self.label_edge_src_image.setText(_translate("merge", "imgae"))
        self.lineEdit_edge_ha.setText(_translate("merge", "100000000000"))
        self.label_ha.setText(_translate("merge", "H_area:"))
        self.label_t2.setText(_translate("merge", "t2:40"))
        self.pushButton_edge_export.setText(_translate("merge", "export"))
        self.label_la_3.setText(_translate("merge", "L_area:"))
        self.label_t1.setText(_translate("merge", "t1:1"))
        self.lineEdit_edge_la.setText(_translate("merge", "2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("merge", "Edge Detection"))
        self.label_flood_src_image.setText(_translate("merge", "imgae"))
        self.image_flood_mask.setText(_translate("merge", "mask"))
        self.image_flood_draw.setText(_translate("merge", "draw"))
        self.pushButton_flood_export.setText(_translate("merge", "export"))
        self.label_diff.setText(_translate("merge", "diff:30"))
        self.pushButton_flood_cancle.setText(_translate("merge", "cancle"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("merge", "Flood Fill"))
        self.label_fig_area.setText(_translate("merge", "area"))
        self.label_fig_line.setText(_translate("merge", "size"))
        self.label_fig_area_max_value.setText(_translate("merge", "Min Value"))
        self.pushButton_open_data_file.setText(_translate("merge", "Open A Data File"))
        self.pushButton_fig_draw.setText(_translate("merge", "draw"))
        self.label_fig_line_max_value.setText(_translate("merge", "Min Value"))
        self.label_fig_line_min_value.setText(_translate("merge", "Max Value"))
        self.label_fig_area_min_value.setText(_translate("merge", "Max Value"))
        self.label_fig_line_increment.setText(_translate("merge", "increment"))
        self.label_fig_area_increment.setText(_translate("merge", "increment"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("merge", "Distribution Figure"))
